<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>BankSystemBackend</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\BankSystemBackend.Domain\BankSystemBackend.Domain.csproj" />
	</ItemGroup>

</Project>
